### PR TITLE
small updates

### PR DESCRIPTION
**Pull request by maxpower-01**
- new .env example file
- new README.md
- added missing docker runtime package (curl)
- updates docker-compose files with health check and dependencies

### CODE REVIEW

**Comment by Fraccaman** [comment]
does `just docker-up` or `just docker-up-d` work?

**Comment by maxpower-01** [comment]
I added a short explanation about both commands in the README.md. I also updated the diagrams and the docs folder.

**Comment by Fraccaman** [comment]
did you check if they work?

**Comment by maxpower-01** [comment]
Hi Fraccaman, Yes it works for me. You see the whole commands in the `justfile` file .

**Pull request merged**
