### PR TITLE
enhancement: store blocks while crawling transactions and chain

### PR DESCRIPTION
**Pull request by joel-u410**

### CODE REVIEW

**Comment by joel-u410** [comment]
Working on fixing tests here -- it's failing because in this branch there is now a foreign key constraint between `balance_changes` --> `blocks` and the tests need to insert blocks before inserting balances.

**Comment by mateuszjasiuk** [comment]
@joel-u410 hello, can you point this to 1.0.0-maint ?

**Comment by joel-u410** [comment]
> @joel-u410 hello, can you point this to 1.0.0-maint ?

Yep, will do!

**Comment by joel-u410** [comment]
So, in https://github.com/anoma/namada-indexer/pull/203 I have added code that resolves `tm_addr` -> `namada_addr` for block proposers.

I'm wondering now if we should do the same here, and store the `namada_address` for block proposers into the `blocks` table instead of the tendermint address as it's currently doing?

@mateuszjasiuk @Fraccaman what do you think?

**Comment by Fraccaman** [comment]
Uhmmm so, in future we will need to have a `fk` to the validator table, so we can join block and validator. Maybe this is something we can do now too? Or do you think it would be too much?

**Comment by joel-u410** [comment]
> Uhmmm so, in future we will need to have a `fk` to the validator table, so we can join block and validator. Maybe this is something we can do now too? Or do you think it would be too much?

That makes sense, especially if `blocks.proposer_address` were storing the `namada_address` of the validator.

Although, I would be concerned about failing to insert a `block` if its `validator` hadn't previously been indexed. I suppose we could insert a stubbed record in that case, to keep the `fk` happy.

I'd like to rebase this one & revisit the `fk` idea after https://github.com/anoma/namada-indexer/pull/203 is merged, since then we will easily have the `namada_address` available for the proposer in each block.

**Comment by joel-u410** [comment]
@mateuszjasiuk I'll take a look today

**Comment by joel-u410** [comment]
> Edit: I tried to test it, but I had some compilation errors. I think it's because you forgot to regenerate diesel schema(the fields in block should be nullable except for height).

Really weird, I didn't have any issues compiling. But makes sense though -- I did change the schema to make those columns nullable, so the diesel schema should indeed be regenerated.

> There was also a problem with initial query for empty db, I think we have to seed db with empty blocks first.

Hmm .. actually it's probably better in that case to query the actual initial block instead of seeding with an empty block. I'll take a closer look.

**Comment by mateuszjasiuk** [comment]
Nice! This works. Thanks for quick response :)

**Review by mateuszjasiuk — APPROVED** [review]

**Pull request merged**
