### PR TITLE
fix webserver healthcheck issue

### PR DESCRIPTION
**Pull request by 0x4r45h**
add curl to the webserver docker image so that the health check can be monitored correctly  
ignore docker-compose.override.* files from the repository for easier customization

### CODE REVIEW

**Comment by Fraccaman** [comment]
i dont get why we need curl?

**Comment by 0x4r45h** [comment]
> i dont get why we need curl?   

@Fraccaman  The webserver service in the docker-compose.yml file has a health check block defined as follows:

```yaml
Copy code
healthcheck:
  test: curl --fail http://localhost:5001/health || exit 1
```  
However, the webserver image does not have the curl command installed. As a result, the health check always fails, incorrectly marking the container as "unhealthy." If you inspect the webserver container, under the health key, you’ll see the corresponding health check errors.

```json

            "Health": {
                "Status": "unhealthy",
                "FailingStreak": 42,
                "Log": [
                    {
                        "Start": "2024-12-13T18:27:05.946254729+01:00",
                        "End": "2024-12-13T18:27:05.976298009+01:00",
                        "ExitCode": 1,
                        "Output": "/bin/sh: 1: curl: not found\n"
                    },
                    {
                        "Start": "2024-12-13T18:27:20.976796091+01:00",
                        "End": "2024-12-13T18:27:21.036034605+01:00",
                        "ExitCode": 1,
                        "Output": "/bin/sh: 1: curl: not found\n"
                    },
                ]
            }
```
To resolve this, we should either:

- Install curl in the webserver image, or
- Modify the health check block in the docker-compose.yml file to use an alternative method.

**Comment by Fraccaman** [comment]
can you rebase on `main` ?

**Comment by 0x4r45h** [comment]
> can you rebase on `main` ?
done

**Pull request merged**
